on:
  release:
    types: [published]

name: Release Build and Push
permissions:
  contents: read
  id-token: write # needed for the Vault authentication

env:
  IMAGE: "rke2-upgrade"
  REPO: "rancher"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
        echo "OS=${{ matrix.os }}"     >> "$GITHUB_ENV"
        echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

    - name: Publish Image
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      if: ${{ !contains(github.ref_name, '-rc') }}
      env:
        ARCH: ${{ matrix.arch }}
        TAG: ${{ github.ref_name }}
        OS: ${{ matrix.os }}
        PRIME_RIBS: ${{ secrets.PRIME_RIBS }}
      with:
        image: ${{ env.IMAGE }}
        tag: ${{ env.GIT_TAG }}-${{ env.ARCH }}
        make-target: push-image

        platforms: ${{ matrix.os }}/${{ matrix.arch }}

        push-to-public: true
        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        push-to-prime: false

  create-manifest:
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change Tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Publish Image - Prime
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        if: ${{ !contains(github.ref_name, '-rc') }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.GIT_TAG }}
          make-target: publish-manifest

          push-to-public: true
          public-repo: ${{ secrets.DOCKER_USERNAME }}
          public-username: ${{ secrets.DOCKER_USERNAME }}
          public-password: ${{ secrets.DOCKER_PASSWORD }}

          push-to-prime: false

      - name: Inspect Prime image
        if: ${{ !contains(github.ref_name, '-rc') }}
        run: docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.GIT_TAG }}
