on:
  release:
    types: [published]

name: tag
permissions:
  contents: read
  id-token: write # needed for the Vault authentication

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
        echo "OS=${{ matrix.os }}"     >> "$GITHUB_ENV"

    - name: Change Tag
      run: |
        echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

    - name: Publish Image - Docker
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      env:
        TAG: ${{ github.ref_name }}
        ARCH: ${{ matrix.arch }}
        OS: ${{ matrix.os }}
      with:
        image: "rke2-upgrade"
        tag: ${{ env.GIT_TAG }}-${{ matrix.arch }}
        make-target: push-image

        public-repo: rancher
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}
        push-to-prime: false

  create-manifest:
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Manifest - Docker
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        with:
          image: "k3s-upgrade"
          tag: ${{ github.ref_name }}
          make-target: publish-manifest

          public-repo: rancher
          public-username: ${{ secrets.DOCKER_USERNAME }}
          public-password: ${{ secrets.DOCKER_PASSWORD }}
          push-to-prime: false

      - name: Inspect Docker image
        run: docker buildx imagetools inspect ${{ env.IMAGE }}:${{ env.VERSION }}
